version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: django_container
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce.settings
      - DJANGO_DEBUG=False
    ports:
      - "80:8000"
    volumes:
      - ./media:/app/media
    restart: always    # Add this line to auto-restart on failure
