# Generated by Django 5.0.2 on 2024-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_caraousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='caraousel',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caraousel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
