# Generated by Django 5.0.6 on 2024-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_caraousel_brand_name_caraousel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('paper_width', models.FloatField()),
                ('paper_height', models.FloatField()),
                ('gram', models.FloatField()),
                ('gram_rate', models.FloatField()),
                ('sheet', models.FloatField()),
                ('labour_cost', models.FloatField()),
                ('boxboard_width', models.FloatField()),
                ('boxboard_height', models.FloatField()),
                ('boxboard_gram', models.FloatField()),
                ('boxboard_rate', models.FloatField()),
                ('boxboard_labour', models.FloatField()),
                ('rolling_cost', models.FloatField()),
                ('additional_labour_cost', models.FloatField()),
                ('printing_cost', models.FloatField()),
                ('lamination_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('total_cost_12', models.FloatField()),
                ('price_per_copy', models.FloatField()),
            ],
        ),
    ]
